window:
  width: 800
  height: 600
  minWidth: 320
  minHeight: 320
editor:
  shiftWidth: 2
  showLineNumbers: true
  relativeLineNumbers: true
  theme:
    fontFamily: "'SF Mono', Monaco, 'Andale Mono', 'Lucida Console', Courier, monospace"
    fontSize: '14px'
    lineHeight: '1.5em'
    primaryColor: '#93a1a1'
    secondaryColor: '#586e75'
    primaryBackgroundColor: '#002b36'
    secondaryBackgroundColor: '#073642'
    cursorColor: '#d33682'
    titleBarHeight: '23px'
